### ISSUE TITLE
Gitlab Fork support - provide remotes in the branch name

### ISSUE THREAD

**Issue by damianoneill** [vishwanatharondekar/gitlab-cli#12]
I have a Gitlab repo (origin) that is forked from another Gitlab repo (upstream).  Both repos have a branch called develop.  

upstream/develop -> forked -> origin/develop -> cloned develop to my laptop.

I make changes in my clone and push to origin.  Then I generate a merge request from origin/develop to upstream/develop.

Can the tool be used to generate a merge request for this?  i.e something like 

gitlab-cli create-merge-request -b origin/develop -t upstream/develop

Thanks in advance.
Damian.

**Comment by vishwanatharondekar** [comment]
We recently added this feature. **It's not really supported the way you want though.** 
You need **two separate branches** with their separate remotes then you can use regular syntax to create merge request between two forks.

Let say develop-origin is branch created from develop and is tracked by remote origin.

```
gitlab-cli create-merge-request -b develop -t develop-origin
```

We don't yet have way to provide support for providing remote in the branch name.
I am editing this issue to reflect the request made. Using supplied remotes we can do what you are asking for.

**Comment by vishwanatharondekar** [comment]
@damianoneill I have made changes in `feature/supplied-remotes` branch. If you have time, you can help me test it by installing it from branch. 

```
npm install https://github.com/vishwanatharondekar/gitlab-cli.git#feature/supplied-remotes -g
```

I will merge it once I have tested it thoroughly. Will take approximately a week.

**Comment by damianoneill** [comment]
@vishwanatharondekar happy to test for you.  

Can you suggest what the command for the merge request should look like given my repo labels above?

To clarify the procedure:

- Central Gitlab Repo (upstream)
- Developer gitlab forks off Central repo (origin)
- Developer clones origin to desktop
- Code change in local desktop, commit and push to origin (developers repo has the latest code).
- Merge request from origin to upstream

Thanks.

**Comment by vishwanatharondekar** [comment]
The command if you install from `feature/supplied-remotes` branch will be following

```
gitlab-cli create-merge-request -b origin/develop -t upstream/develop
```

Please note that this requires that you have upstream and origin added as remote in your local with respected repository url set.
```
> git remote -v 
```

Above should have upstream and origin both set properly. It should work then with above gitlab-cli command.

**Comment by damianoneill** [comment]
HI @vishwanatharondekar, see below.

$ git remote -v
origin	git@git.acme.net:origin/joc.git (fetch)
origin	git@git.acme.net:origin/joc.git (push)
upstream	git@git.acme.net:upstream/joc.git (fetch)
upstream	git@git.acme.net:upstream/joc.git (push)

$ gitlab-cli create-merge-request -b origin/develop -t upstream/develop -v
verbose option used. Detailed logging information will be emitted.



Getting base branch information

Getting base branch name :
Argument provided : origin/develop
Branch name obtained : origin/develop
Base branch name obtained : origin/develop

Getting remote of branch  : origin/develop
Branch name obtained : origin/develop
Executing git config branch.origin/develop.remote
Error occured :
 Error: Command failed: git config branch.origin/develop.remote

**Comment by vishwanatharondekar** [comment]
@damianoneill Did you install from the branch feature/supplied-remotes?

**Comment by damianoneill** [comment]
Yes see below. 

doneill at doneill-mbp in ~/projects/gitlab/joc on develop
$ npm install https://github.com/vishwanatharondekar/gitlab-cli.git#feature/supplied-remotes -g
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/bin/gitlab-cli -> /usr/local/lib/node_modules/gitlab-cli/index.js
/usr/local/lib
└── gitlab-cli@1.0.0  (git+https://github.com/vishwanatharondekar/gitlab-cli.git#fd304f877bdf5c6261bb0bb6793b01e58bdcb18f)

**Comment by damianoneill** [comment]
Hi @vishwanatharondekar I can changed the command to below, I removed the base remote and it seemed to work ok.  

I'll do some further testing this week.

$ gitlab-cli create-merge-request -b develop -t upstream/develop

**Comment by damianoneill** [comment]
@vishwanatharondekar is it possible to extend this functionality to the open-merge-requests command.  So that the user can open the merge page of the remote?

@vishwanatharondekar I meant to say, thanks very much for the tool, this will save us a load of time in our development cycle.

Damian.

**Comment by vishwanatharondekar** [comment]
@damianoneill I tested it again by re-installing from remote branch just to be sure. Works fine for first command as well. 

Also, the logs you shared looks like of master. Can you try again with the command we supplied at first. Btw, it will work for all cases. Almost everything is optional and almost everything can be provided.

**Comment by vishwanatharondekar** [comment]
Create separate issue if you need new feature to be added. Currently it opens the merge request page created. Do you want **all merge requests** page to be opened?

**Comment by damianoneill** [comment]
This fails

$ gitlab-cli create-merge-request -b origin/develop -t upstream/develop
Error occured :
 Error: Command failed: git config branch.origin/develop.remote

Below works fine.

doneill at doneill-mbp in ~/projects/gitlab/joc on develop
$ gitlab-cli create-merge-request -b develop -t upstream/develop

**Comment by vishwanatharondekar** [comment]
Will check on some other machine when I have it available on Monday. I am not able to re-produce the issue as of now.

**Comment by damianoneill** [comment]
@vishwanatharondekar been using the branch with no issues, today it stopped working.  

When I run it now I get the following error 

```
.git/PULL_REQUEST_TITLE [+]                                                                                                                                                      1,13           All
".git/PULL_REQUEST_TITLE"
".git/PULL_REQUEST_TITLE" E212: Can't open file for writing
```

This occurs straight after 

```
Target project info obtained : { ... }
```

I removed the content from the json object above.  

it opens a vi session to this file, it includes no contents.  If I try to write / close I get the error above above.  

If I close no write I get 

```
$ gitlab-cli create-merge-request -b develop -t upstream/develop
/usr/local/lib/node_modules/gitlab-cli/index.js:61
            logger.log('Input obtained using editor: ', title.green);
                                                             ^

TypeError: Cannot read property 'green' of undefined
    at ReadFileContext.callback (/usr/local/lib/node_modules/gitlab-cli/index.js:61:62)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:336:13)

```

**Comment by vishwanatharondekar** [comment]
You are probably in sub directory of the repository. This happened with me as well. Check if you are not at the sub-directory.

**Comment by damianoneill** [comment]
Thanks @vishwanatharondekar that worked.  Is it possible to update the solution so that you dont have to be at the top level?  

Separately I have another issue, looks like our gitlab server is load balanced to an gitlab instance and the output is being dumped to the console, see below

```
$ gitlab-cli create-merge-request -b develop -t upstream/develop
mergeRequestResponse :  <html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by vishwanatharondekar** [comment]
Will remove the output you see. I think it was added by me for debugging. We don't need that.
Will create separate issue for being at top level. Will be at bottom on my priority list though.

Btw can you test the original case again by re-installing the latest code from branch. I had done some fixes after we last talked.

**Comment by damianoneill** [comment]
Just installed from the latest branch, went through the process as normal, used the above command.  It gets to this point 

```
...

Getting merge request title. Argument provided :  undefined
Input obtained using editor:  test commit


Merge request title :  test commit


Creating merge request

```

Nothing more to console after the above. 

No merge request was created on upstream/develop

**Comment by vishwanatharondekar** [comment]
Will need the whole output. Can you post the complete outout with verbose option.

**Comment by damianoneill** [comment]
I'm sure you understand, I have replaced the real project names and server urls 

```
doneill at doneill-mbp in ~/projects/gitlab/joc on develop
$ gitlab-cli create-merge-request -b origin/develop -t upstream/develop -v
verbose option used. Detailed logging information will be emitted.



Getting base branch information

Getting base branch name :
Argument provided : origin/develop
Branch name obtained : develop
Base branch name obtained : develop

Getting remote of branch  : origin/develop
Branch name obtained : develop
Remote obtained :  origin

Getting URL of remote :  origin
Executing  git config remote.origin.url
URL of remote obtained :  git@git.acme.net:origin/joc.git


gitlab host obtained :  git.acme.net

Project name derived from host : origin/joc

Getting gitlab project info for : origin/joc
Base project info obtained : {"id":1984,"description":"Next Generation using upstream Infrastructure framework","default_branch":"develop","tag_list":[],"public":false,"archived":false,"visibi


1   test commit
lity_level":0,"ssh_url_to_repo":"git@git.acme.net:origin/joc.git","http_url_to_repo":"https://git.acme.net/origin/joc.git","web_url":"https://git.acme.net/origin/joc","owner":{"name":"Damian O'Neill","username":"origin","id":1294,"state":"active","avatar_url":null,"web_url":"https://git.acme.net/origin"},"name":"joc","name_with_namespace":"Damian O'Neill / joc","path":"joc","path_with_namespace":"origin/joc","container_registry_enabled":true,"issues_enabled":true,"merge_requests_enabled":true,"wiki_enabled":true,"builds_enabled":true,"snippets_enabled":false,"created_at":"2016-12-13T14:27:16.932Z","last_activity_at":"2017-01-19T16:34:03.092Z","shared_runners_enabled":true,"lfs_enabled":true,"creator_id":1294,"namespace":{"id":1355,"name":"origin","path":"origin","owner_id":1294,"created_at":"2016-08-04T14:46:51.931Z","updated_at":"2016-08-04T14:46:51.931Z","description":"","avatar":null,"membership_lock":false,"share_with_group_lock":false,"visibility_level":20,"request_access_enabled":true,"ldap_sync_status":"ready","ldap_sync_error":null,"ldap_sync_last_update_at":null,"ldap_sync_last_successful_update_at":null,"ldap_sync_last_sync_at":null,"deleted_at":null,"lfs_enabled":null,"repository_size_limit":null,"parent_id":null},"forked_from_project":{"id":1402,"http_url_to_repo":"https://git.acme.net/upstream/joc.git","web_url":"https://git.acme.net/upstream/joc","name":"joc","name_with_namespace":"upstream / joc","path":"joc","path_with_namespace":"upstream/joc"},"avatar_url":null,"star_count":0,"forks_count":0,"open_issues_count":0,"runners_token":"z_qU32_9n1NCZkuxEsHe","public_builds":true,"shared_with_groups":[],"only_allow_merge_if_build_succeeds":false,"request_access_enabled":false,"only_allow_merge_if_all_discussions_are_resolved":false,"approvals_before_merge":0,"permissions":{"project_access":{"access_level":40,"notification_level":3},"group_access":null}}



Getting target branch information
Branch name obtained : develop
Remote branch name obtained : develop

Getting remote of branch  : upstream/develop
Branch name obtained : develop
Remote obtained :  upstream

Getting URL of remote :  upstream
Executing  git config remote.upstream.url
URL of remote obtained :  git@git.acme.net:upstream/joc.git

Getting target project information
Target project info obtained : {"id":1402,"description":"Next Generation using upstream Infrastructure framework","default_branch":"develop","tag_list":[],"public":false,"archived":false,"visibility_level":0,"ssh_url_to_repo":"git@git.acme.net:upstream/joc.git","http_url_to_repo":"https://git.acme.net/upstream/joc.git","web_url":"https://git.acme.net/upstream/joc","name":"joc","name_with_namespace":"upstream / joc","path":"joc","path_with_namespace":"upstream/joc","container_registry_enabled":true,"issues_enabled":true,"merge_requests_enabled":true,"wiki_enabled":true,"builds_enabled":true,"snippets_enabled":true,"created_at":"2016-10-17T10:57:16.538Z","last_activity_at":"2017-01-19T15:17:02.513Z","shared_runners_enabled":true,"lfs_enabled":true,"creator_id":1294,"namespace":{"id":1796,"name":"upstream","path":"upstream","owner_id":null,"created_at":"2016-10-17T10:55:16.179Z","updated_at":"2016-10-17T10:55:16.179Z","description":"Placeholder for all software projects running under the upstream NPI","avatar":{"url":null},"membership_lock":false,"share_with_group_lock":false,"visibility_level":0,"request_access_enabled":true,"ldap_sync_status":"ready","ldap_sync_error":null,"ldap_sync_last_update_at":null,"ldap_sync_last_successful_update_at":null,"ldap_sync_last_sync_at":null,"deleted_at":null,"lfs_enabled":null,"repository_size_limit":null,"parent_id":null},"avatar_url":null,"star_count":1,"forks_count":10,"open_issues_count":0,"runners_token":"eDMmzajA1wz4R_na1df3","public_builds":true,"shared_with_groups":[],"only_allow_merge_if_build_succeeds":false,"request_access_enabled":true,"only_allow_merge_if_all_discussions_are_resolved":false,"approvals_before_merge":1,"permissions":{"project_access":null,"group_access":{"access_level":50,"notification_level":3}}}

Getting merge request title. Argument provided :  undefined
Input obtained using editor:  test commit


Merge request title :  test commit


Creating merge request
doneill at doneill-mbp in ~/projects/gitlab/joc on develop
```

**Comment by vishwanatharondekar** [comment]
Thanks for the log. Everything looks fine though. Merge request should have got created. Is it only this command that doesn't work, and some other way of doing it works fine.

**Comment by damianoneill** [comment]
Yes, if I go to the origin server and generate the merge from there through the gitlab user interface it works fine.

**Comment by vishwanatharondekar** [comment]
@damianoneill 
I meant other command syntax without origin in the branch name.

**Comment by damianoneill** [comment]
```
$ gitlab-cli create-merge-request -b develop -t upstream/develop
```

Same result, no error message, no merge request created.

**Comment by vishwanatharondekar** [comment]
Not good. This was working before right?

**Comment by damianoneill** [comment]
Yes working before.  I am home today over VPN so will try tomorrow in work to confirm not a routing issue.

**Comment by damianoneill** [comment]
I've testing this morning behaviour is still the same.  

I checked out and built the first version you gave me which definitely worked previously, this is now not working, so it suggests its a problem on my side. 

I've removed and rebuilt the clone with no effect.  I'll try the same with the fork now.  

Is it possible to update the -v output to show the exact API request that gets sent to the gitlab instance?

**Comment by vishwanatharondekar** [comment]
-v can not probably give you the request since I have used other library which does it internally but I can add the response of it. Will do that and push to master.

**Comment by damianoneill** [comment]
Ok, thanks.  

I removed and rebuilt my fork, this made no difference, same issue.

**Comment by vishwanatharondekar** [comment]
@damianoneill added merge request response in -v option in master and feature/supplied-remotes branch. You can check whats happening with that. Looks like something has changed on your side for sure.

**Comment by damianoneill** [comment]
@vishwanatharondekar hasnt helped much, just showing the response from previously that your omitted 

```
Creating merge request
Merge request response :

 <html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
 ```

**Comment by damianoneill** [comment]
@vishwanatharondekar could the problem be that the underlying http module used by your library is not following http redirects?

**Comment by vishwanatharondekar** [comment]
@damianoneill 
Looks like that. I earlier had `unirest` as http library which I removed in favour of node-gitlab. It was giving me https errors and couldn't handle them without some hacks on local machines.

Where is this getting redirected to? Can you try changing your GITLAB_URL to where its getting redirected.

I think it must have stopped working recently for you after your gitlab instance moved to some other URL. http to https maybe.

**Comment by vishwanatharondekar** [comment]
@damianoneill I am merging the PR related to this issue and closing this issue. In my testing it works fine, I have fixed the bugs I found.

This new problem you reported looks like a separate issue with http communication. You can create separate issue for that. We will need more info to debug that though. 

Will wait for 24 hours before merging. Let me know if you have anything.

**Comment by vishwanatharondekar** [comment]
Merging PR related to this.
