### ISSUE TITLE
Cannot read property 'green' of undefined

### ISSUE THREAD

**Issue by sunshaobei** [vishwanatharondekar/gitlab-cli#124]
return "Cannot read property 'green' of undefined" when i try to user commandline  lab merge-request -b develop - t release

**Comment by cybercode** [comment]
Same issue. I have tracked it down to line 370 in index.js: `return gitlab.Projects.search(projectName);` returning no projects, which  leads to line 373 `logger.log('Base project info obtained :', JSON.stringify(project).green)` failing.

This is with: `gitlab-ee/xenial,now 13.9.3-ee.0 amd64`

**Comment by vishwanatharondekar** [comment]
I don't have access to gitlab-ee now. Will be great if someone can help with this.

**Comment by vishwanatharondekar** [comment]
Fixed in https://github.com/vishwanatharondekar/gitlab-cli/pull/139. Reopen if still facing the issue.
