### ISSUE TITLE
Feature Request - remote support for open-merge-requests

### ISSUE THREAD

**Issue by damianoneill** [vishwanatharondekar/gitlab-cli#14]
To extend the open-merge-requests command to take an argument.

The argument will be a remote, the command should open the merge web page of the repo associated with the remote.

For e.g. if a remote is defined called upstream(git@git.acme.net:upstream/joc.git) the command may look as below.

$ gitlab-cli open-merge-requests -r upstream

And open the webpage at 

https://git.acme.net/upstream/joc/merge_requests

**Comment by vishwanatharondekar** [comment]
Got it. Should be easy after we merge https://github.com/vishwanatharondekar/gitlab-cli/pull/13 . Will create branch from feature/supplied-remotes and keep it ready. Will merge after we have merged https://github.com/vishwanatharondekar/gitlab-cli/pull/13
