### ISSUE TITLE
Latest 2.0.10 version merge request broked

### ISSUE THREAD

**Issue by LeeJunhui** [vishwanatharondekar/gitlab-cli#145]
2.0.7 works fine, but the latest version failed at gitlab.Projects.search, the error message is 401, not authorized.

**Comment by vishwanatharondekar** [comment]
Will have a look. I changed the underlying gitlab api package. Can you share some more info as to what version of gitlab you are on. And log of the command by using -v option.

**Comment by vishwanatharondekar** [comment]
Closing this since log asked for is not provided. Feel free to reopen with the log .
