### ISSUE TITLE
Response code 401 (Unauthorized)

### ISSUE THREAD

**Issue by HeeBooo** [vishwanatharondekar/gitlab-cli#165]
![image](https://user-images.githubusercontent.com/23186355/132157588-14804dac-96e2-41d9-93c6-b5d1a92234a7.png)
![image](https://user-images.githubusercontent.com/23186355/132157616-dc7006c5-13bc-415d-bc3c-e692501565a1.png)
![image](https://user-images.githubusercontent.com/23186355/132157651-aedf9c24-bed0-41b0-859d-98aea96acd75.png)

**Comment by vishwanatharondekar** [comment]
Can you check if it works on the command line properly and fails only with execSync?

**Comment by HeeBooo** [comment]
> Can you check if it works on the command line properly and fails only with execSync?

yes，it works on the command 
![image](https://user-images.githubusercontent.com/23186355/132166217-ed81956f-7da4-4621-85a4-a6a840c0a474.png)
![image](https://user-images.githubusercontent.com/23186355/132166265-0834cb35-373e-421c-8559-f634358af7fc.png)
but when i use execSync, it throw Couldn't create merge request and 401

**Comment by HeeBooo** [comment]
I have solved it, in package-lock.json file, the version is 2.0.10, i update it to 2.0.7

**Comment by yulongfy** [comment]
> I have solved it, in package-lock.json file, the version is 2.0.10, i update it to 2.0.7

xiongdi , why i still got a 401 when a update 2.0.10 to 2.0.7, can u  give me a detailed operation method？ 3ks

**Comment by HeeBooo** [comment]
> > I have solved it, in package-lock.json file, the version is 2.0.10, i update it to 2.0.7
> 
> xiongdi , why i still got a 401 when a update 2.0.10 to 2.0.7, can u give me a detailed operation method？ 3ks

你看下你package-lock文件夹
![image](https://user-images.githubusercontent.com/23186355/132667771-dec88b85-0ea3-40e4-b278-7d21724f19f7.png)
是不是2.0.7版本

**Comment by HeeBooo** [comment]
> > > I have solved it, in package-lock.json file, the version is 2.0.10, i update it to 2.0.7
> > 
> > 
> > xiongdi , why i still got a 401 when a update 2.0.10 to 2.0.7, can u give me a detailed operation method？ 3ks
> 
> 你看下你package-lock文件夹
> ![image](https://user-images.githubusercontent.com/23186355/132667771-dec88b85-0ea3-40e4-b278-7d21724f19f7.png)
> 是不是2.0.7版本

**Comment by HeeBooo** [comment]
> > > > I have solved it, in package-lock.json file, the version is 2.0.10, i update it to 2.0.7
> > > 
> > > 
> > > xiongdi , why i still got a 401 when a update 2.0.10 to 2.0.7, can u give me a detailed operation method？ 3ks
> > 
> > 
> > 你看下你package-lock文件夹
> > ![image](https://user-images.githubusercontent.com/23186355/132667771-dec88b85-0ea3-40e4-b278-7d21724f19f7.png)
> > 是不是2.0.7版本

**Comment by vishwanatharondekar** [comment]
There seem to be some issue in 2.0.10 which is not there is 2.0.7. Will check.

**Comment by vishwanathd11** [comment]
Closing since no response.
