### ISSUE TITLE
Re-factor code into smaller modules

### ISSUE THREAD

**Issue by vishwanatharondekar** [vishwanatharondekar/gitlab-cli#17]
When I started writing this utility. Didn't expect it to grow like it has now. Will want to re-factor the code into smaller modules so maintenance / enhancements will not be a pain.

**Comment by vishwanatharondekar** [comment]
Starting work on this. Have decided to use async waterfall strategy to cleanup the promise mess.

**Comment by vishwanatharondekar** [comment]
Using execSync is better option than async waterfall. Moving to that.

**Comment by stevelacey** [comment]
Maybe add some tests ahead of this – would make it a tonne easier. Hub uses Cucumber.

**Comment by vishwanatharondekar** [comment]
Code needs to be testable for us to write test cases. I am not sure if current code is testable enough. Breaking it into small modules will help. Rather I can start doing test case setup and that will make the code modular and testable in the process.
