### ISSUE TITLE
How do I need to set the project name

### ISSUE THREAD

**Issue by Naist4869** [vishwanatharondekar/gitlab-cli#179]
Hi, good job  @vishwanathd11 
The problem arises because the default project name is not the one I want

```bash
lab merge-request -t equator -m aa -v
```

got: gitlab.com:nova_dubai/first-web.git   // The first of all my projects
want: gitlab.com:nova_dubai/first.git

Thanks

```code 
Verbose option used. Detailed logging information will be emitted.



Getting base branch information

Getting base branch name : 
Executing git rev-parse --abbrev-ref HEAD
Base branch name obtained : master

Getting remote of branch : master
Executing git config branch.master.remote
Remote obtained : origin


Getting URL of remote : origin
Executing  git config remote.origin.url
URL of remote obtained : git@gitlab.com:nova_dubai/first.git


gitlab host obtained : gitlab.com

Project name derived from host : nova_dubai/first

Getting gitlab project info for : nova_dubai/first
Base project info obtained : {"id":32506476,"description":"","name":"刷单后台","name_with_namespace":"nova_dubai / 刷单后台","path":"first-web","path_with_namespace":"nova_dubai/first-web","created_at":"2022-01-02T13:11:59.643Z","default_branch":"main","tag_list":[],"topics":[],"ssh_url_to_repo":"git@gitlab.com:nova_dubai/firit","http_url_to_repo":"https://gitlab.com/nova_dubai/first-web.git","web_url":"https://gitlab.com/nova_dubai/first-web","readme_url":null,"avatar_url":null,"forks_count":0,"star_count":0,"last_activity_at":"2022-01-15T23:23:36.075Z","namespace":{"id":12048031,"name":"nova_dubai","path":"nova_dubai","kind":"group","full_path":"nova_dubai","parent_id":null,"avatar_url":null,"web_url":"https://gitlab.com/groups/nova_dubai"},"container_registry_image_prefix":"registry.gitlab.com/nova_dubai/first-web","_links":{"self":"https://gitlab.com/api/v4/projects/32506476","issues":"https://gitlab.com/api/v4/projects/32506476/issues","merge_requests":"https://gitlab.com/api/v4/projects/32506476/merge_requests","repo_branches":"https://gitlab.com/api/v4/projects/32506476/repository/branches","labels":"https://gitlab.com/api/v4/projects/32506476/labels","events":"https://gitlab.com/api/v4/projects/32506476/events","members":"https://gitlab.com/api/v4/projects/32506476/members"},"packages_enabled":true,"empty_repo":true,"archived":false,"visibility":"private","resolve_outdated_diff_discussions":false,"container_expiration_policy":{"cadence":"1d","enabled":false,"keep_n":10,"older_than":"90d","name_regex":".*","name_regex_keep":null,"next_run_at":"2022-01-03T13:11:59.661Z"},"issues_enabled":true,"merge_requests_enabled":true,"wiki_enabled":true,"jobs_enabled":true,"snippets_enabled":true,"container_registry_enabled":true,"service_desk_enabled":true,"service_desk_address":"contact-project+nova-dubai-first-web-32506476-issue-@incoming.gitlab.com","can_create_merge_request_in":true,"issues_access_level":"enabled","repository_access_level":"enabled","merge_requests_access_level":"enabled","forking_access_level":"enabled","wiki_access_level":"enabled","builds_access_level":"enabled","snippets_access_level":"enabled","pages_access_level":"private","operations_access_level":"enabled","analytics_access_level":"enabled","container_registry_access_level":"enabled","emails_disabled":null,"shared_runners_enabled":true,"lfs_enabled":true,"creator_id":713145,"import_status":"none","open_issues_count":0,"ci_default_git_depth":50,"ci_forward_deployment_enabled":true,"ci_job_token_scope_enabled":false,"public_jobs":true,"build_timeout":3600,"auto_cancel_pending_pipelines":"enabled","build_coverage_regex":null,"ci_config_path":"","shared_with_groups":[],"only_allow_merge_if_pipeline_succeeds":false,"allow_merge_on_skipped_pipeline":null,"restrict_user_defined_variables":false,"request_access_enabled":true,"only_allow_merge_if_all_discussions_are_resolved":false,"remove_source_branch_after_merge":true,"printing_merge_request_link_enabled":true,"merge_method":"merge","squash_option":"default_off","suggestion_commit_message":null,"merge_commit_template":null,"squash_commit_template":null,"auto_devops_enabled":false,"auto_devops_deploy_strategy":"continuous","autoclose_referenced_issues":true,"keep_latest_artifact":true,"external_authorization_classification_label":"","requirements_enabled":false,"security_and_compliance_enabled":true,"compliance_frameworks":[],"permissions":{"project_access":null,"group_access":{"access_level":30,"notification_level":null}}}



Getting target branch information
Remote branch name obtained : equator

Getting remote of branch : equator
Executing git config branch.equator.remote
Remote obtained : origin


Getting URL of remote : origin
Executing  git config remote.origin.url
URL of remote obtained : git@gitlab.com:nova_dubai/first.git

Getting target project information
Target project info obtained : {"id":32506476,"description":"","name":"刷单后台","name_with_namespace":"nova_dubai / 刷单后台","path":"first-web","path_with_namespace":"nova_dubai/first-web","created_at":"2022-01-02T13:11:59.643Z","default_branch":"main","tag_list":[],"topics":[],"ssh_url_to_repo":"git@gitlab.com:nova_dubai/f.git","http_url_to_repo":"https://gitlab.com/nova_dubai/first-web.git","web_url":"https://gitlab.com/nova_dubai/first-web","readme_url":null,"avatar_url":null,"forks_count":0,"star_count":0,"last_activity_at":"2022-01-15T23:23:36.075Z","namespace":{"id":12048031,"name":"nova_dubai","path":"nova_dubai","kind":"group","full_path":"nova_dubai","parent_id":null,"avatar_url":null,"web_url":"https://gitlab.com/groups/nova_dubai"},"container_registry_image_prefix":"registry.gitlab.com/nova_dubai/first-web","_links":{"self":"https://gitlab.com/api/v4/projects/32506476","issues":"https://gitlab.com/api/v4/projects/32506476/issues","merge_requests":"https://gitlab.com/api/v4/projects/32506476/merge_requests","repo_branches":"https://gitlab.com/api/v4/projects/32506476/repository/branches","labels":"https://gitlab.com/api/v4/projects/32506476/labels","events":"https://gitlab.com/api/v4/projects/32506476/events","members":"https://gitlab.com/api/v4/projects/32506476/members"},"packages_enabled":true,"empty_repo":true,"archived":false,"visibility":"private","resolve_outdated_diff_discussions":false,"container_expiration_policy":{"cadence":"1d","enabled":false,"keep_n":10,"older_than":"90d","name_regex":".*","name_regex_keep":null,"next_run_at":"2022-01-03T13:11:59.661Z"},"issues_enabled":true,"merge_requests_enabled":true,"wiki_enabled":true,"jobs_enabled":true,"snippets_enabled":true,"container_registry_enabled":true,"service_desk_enabled":true,"service_desk_address":"contact-project+nova-dubai-first-web-32506476-issue-@incoming.gitlab.com","can_create_merge_request_in":true,"issues_access_level":"enabled","repository_access_level":"enabled","merge_requests_access_level":"enabled","forking_access_level":"enabled","wiki_access_level":"enabled","builds_access_level":"enabled","snippets_access_level":"enabled","pages_access_level":"private","operations_access_level":"enabled","analytics_access_level":"enabled","container_registry_access_level":"enabled","emails_disabled":null,"shared_runners_enabled":true,"lfs_enabled":true,"creator_id":713145,"import_status":"none","open_issues_count":0,"ci_default_git_depth":50,"ci_forward_deployment_enabled":true,"ci_job_token_scope_enabled":false,"public_jobs":true,"build_timeout":3600,"auto_cancel_pending_pipelines":"enabled","build_coverage_regex":null,"ci_config_path":"","shared_with_groups":[],"only_allow_merge_if_pipeline_succeeds":false,"allow_merge_on_skipped_pipeline":null,"restrict_user_defined_variables":false,"request_access_enabled":true,"only_allow_merge_if_all_discussions_are_resolved":false,"remove_source_branch_after_merge":true,"printing_merge_request_link_enabled":true,"merge_method":"merge","squash_option":"default_off","suggestion_commit_message":null,"merge_commit_template":null,"squash_commit_template":null,"auto_devops_enabled":false,"auto_devops_deploy_strategy":"continuous","autoclose_referenced_issues":true,"keep_latest_artifact":true,"external_authorization_classification_label":"","requirements_enabled":false,"security_and_compliance_enabled":true,"compliance_frameworks":[],"permissions":{"project_access":null,"group_access":{"access_level":30,"notification_level":null}}}

Getting merge request title. Argument provided : aa
Title obtained with -m option: aa
Merge request title : aa
Merge request description : undefined


Creating merge request
Merge request response: 

 {
  id: 135356651,
  iid: 3,
  project_id: 32506476,
  title: 'aa',
  description: null,
  state: 'opened',
  created_at: '2022-01-15T23:53:25.458Z',
  updated_at: '2022-01-15T23:53:25.458Z',
  merged_by: null,
  merged_at: null,
  closed_by: null,
  closed_at: null,
  target_branch: 'equator',
  source_branch: 'master',
  user_notes_count: 0,
  upvotes: 0,
  downvotes: 0,
  author: {
    id: 9114706,
    username: 'Naist4869',
    name: 'Naist4869',
    state: 'active',
    avatar_url: 'https://secure.gravatar.com/avatar/0f0f86d6a5dc99ca7bc0231d78ed1cd4?s=80&d=identicon',
    web_url: 'https://gitlab.com/Naist4869'
  },
  assignees: [],
  assignee: null,
  reviewers: [],
  source_project_id: 32506476,
  target_project_id: 32506476,
  labels: [],
  draft: false,
  work_in_progress: false,
  milestone: null,
  merge_when_pipeline_succeeds: false,
  merge_status: 'checking',
  sha: null,
  merge_commit_sha: null,
  squash_commit_sha: null,
  discussion_locked: null,
  should_remove_source_branch: null,
  force_remove_source_branch: false,
  reference: '!3',
  references: { short: '!3', relative: '!3', full: 'nova_dubai/first-web!3' },
  web_url: 'https://gitlab.com/nova_dubai/first-web/-/merge_requests/3',
  time_stats: {
    time_estimate: 0,
    total_time_spent: 0,
    human_time_estimate: null,
    human_total_time_spent: null
  },
  squash: false,
  task_completion_status: { count: 0, completed_count: 0 },
  has_conflicts: false,
  blocking_discussions_resolved: true,
  approvals_before_merge: null,
  subscribed: true,
  changes_count: null,
  latest_build_started_at: null,
  latest_build_finished_at: null,
  first_deployed_to_production_at: null,
  pipeline: null,
  head_pipeline: null,
  diff_refs: null,
  merge_error: null,
  user: { can_merge: false }
}


```

**Comment by vishwanatharondekar** [comment]
Is the PR between two forks or something like that? Branch names have support for providing origin.

If the PR is between let say two different origins named  upstream and downstream. You can create the PR like following.

```
lab merge-request -t upstream/equator -b origin/equator
```

Let me know if this works for you or if you need more details.
Replied from phone.

**Comment by Naist4869** [comment]
i mean Target project

not Base branch or Target branch

**Comment by vishwanatharondekar** [comment]
Branch has support for project. It needs to be configured as newly added origin. Then the above command will work for creating PR between two projects.

Replied from Phone.

**Comment by vishwanatharondekar** [comment]
Imagine you have two projects Project A and Project B (Forked from Project A or some kind of relation - if these two are independent projects then you cant create PR between them)

if you have setup like above, you must be having two origins named origin and upstream setup in your git config. 

```
# some config here
[remote "origin"]
	url = git@github.com:vishwanathd11/medium-2-md.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[remote "upstream"]
	url = git@github.com:gautamdhameja/medium-2-md.git
	fetch = +refs/heads/*:refs/remotes/origin/*
# some config here
```

In this case you can use following command to create PR between these two projects with following 

```
lab merge-request -t upstream/master -b origin/equator
```

This will create PR on target project gautamdhameja/medium-2-md.git on master branch with my equator branch.  You may change the branch if needed .

**Comment by Naist4869** [comment]
I use 2.0.7 finish work  
thanks your help

Verbose option used. Detailed logging information will be emitted.



Getting base branch information

Getting base branch name : 
Executing git rev-parse --abbrev-ref HEAD
Base branch name obtained : test2

Getting remote of branch : test2
Executing git config branch.test2.remote
Remote obtained : origin


Getting URL of remote : origin
Executing  git config remote.origin.url
URL of remote obtained : git@gitlab.com:nova_dubai/first.git


gitlab host obtained : gitlab.com

Project name derived from host : nova_dubai/first

Getting gitlab project info for : nova_dubai/first
Base project info obtained : {"id":31358341,"description":"跑分","name":"first","name_with_namespace":"nova_dubai / first","path":"first","path_with_namespace":"nova_dubai/first","created_at":"2021-11-16T11:06:05.725Z","default_branch":"master","tag_list":[],"topic:[],"ssh_url_to_repo":"git@gitlab.com:nova_dubai/first.git","http_url_to_repo":"https://gitlab.com/nova_dubai/first.git","web_url":"https://gitlab.com/nova_dubai/first","readme_url":"https://gitlab.com/nova_dubai/first/-/blob/master/README.md","avatar_url":null,"forks_count":0,"star_count":0,"last_activity_at":"2022-01-17T18:02:31.670Z","namespace":{"id":12048031,"name":"nova_dubai","path":"nova_dubai","kind":"group","full_path":"nova_dubai","parent_id":null,"avatar_url":null,"web_url":"https://gitlab.com/groups/nova_dubai"},"container_registry_image_prefix":"registry.gitlab.com/nova_dubai/first","_links":{"self":"https://gitlab.com/api/v4/projects/31358341","issues":"https://gitlab.com/api/v4/projects/31358341/issues","merge_requests":"https://gitlab.com/api/v4/projects/31358341/merge_requests","repo_branches":"https://gitlab.com/api/v4/projects/31358341/repository/branches","labels":"https://gitlab.com/api/v4/projects/31358341/labels","events":"https://gitlab.com/api/v4/projects/31358341/events","members":"https://gitlab.com/api/v4/projects/31358341/members"},"packages_enabled":true,"empty_repo":false,"archived":false,"visibility":"private","resolve_outdated_diff_discussions":false,"container_expiration_policy":{"cadence":"1d","enabled":false,"keep_n":10,"older_than":"90d","name_regex":".*","name_regex_keep":null,"next_run_at":"2021-11-17T11:06:05.761Z"},"issues_enabled":true,"merge_requests_enabled":true,"wiki_enabled":true,"jobs_enabled":true,"snippets_enabled":true,"container_registry_enabled":true,"service_desk_enabled":true,"service_desk_address":"contact-project+nova-dubai-first-31358341-issue-@incoming.gitlab.com","can_create_merge_request_in":true,"issues_access_level":"enabled","repository_access_level":"enabled","merge_requests_access_level":"enabled","forking_access_level":"enabled","wiki_access_level":"enabled","builds_access_level":"enabled","snippets_access_level":"enabled","pages_access_level":"private","operations_access_level":"enabled","analytics_access_level":"enabled","container_registry_access_level":"enabled","emails_disabled":null,"shared_runners_enabled":true,"lfs_enabled":true,"creator_id":713145,"import_status":"none","open_issues_count":1,"ci_default_git_depth":50,"ci_forward_deployment_enabled":true,"ci_job_token_scope_enabled":false,"public_jobs":true,"build_timeout":3600,"auto_cancel_pending_pipelines":"enabled","build_coverage_regex":null,"ci_config_path":"","shared_with_groups":[],"only_allow_merge_if_pipeline_succeeds":false,"allow_merge_on_skipped_pipeline":null,"restrict_user_defined_variables":false,"request_access_enabled":true,"only_allow_merge_if_all_discussions_are_resolved":false,"remove_source_branch_after_merge":true,"printing_merge_request_link_enabled":true,"merge_method":"merge","squash_option":"default_off","suggestion_commit_message":null,"merge_commit_template":null,"squash_commit_template":null,"auto_devops_enabled":false,"auto_devops_deploy_strategy":"continuous","autoclose_referenced_issues":true,"keep_latest_artifact":true,"external_authorization_classification_label":"","requirements_enabled":false,"security_and_compliance_enabled":true,"compliance_frameworks":[],"permissions":{"project_access":null,"group_access":{"access_level":30,"notification_level":3}}}



Getting target branch information
Remote branch name obtained : master

Getting remote of branch : master
Executing git config branch.master.remote
Remote obtained : origin


Getting URL of remote : origin
Executing  git config remote.origin.url
URL of remote obtained : git@gitlab.com:nova_dubai/first.git

Getting target project information
Target project info obtained : {"id":31358341,"description":"跑分","name":"first","name_with_namespace":"nova_dubai / first","path":"first","path_with_namespace":"nova_dubai/first","created_at":"2021-11-16T11:06:05.725Z","default_branch":"master","tag_list":[],"tops":[],"ssh_url_to_repo":"git@gitlab.com:nova_dubai/first.git","http_url_to_repo":"https://gitlab.com/nova_dubai/first.git","web_url":"https://gitlab.com/nova_dubai/first","readme_url":"https://gitlab.com/nova_dubai/first/-/blob/master/README.md","avatar_url":null,"forks_count":0,"star_count":0,"last_activity_at":"2022-01-17T18:02:31.670Z","namespace":{"id":12048031,"name":"nova_dubai","path":"nova_dubai","kind":"group","full_path":"nova_dubai","parent_id":null,"avatar_url":null,"web_url":"https://gitlab.com/groups/nova_dubai"},"container_registry_image_prefix":"registry.gitlab.com/nova_dubai/first","_links":{"self":"https://gitlab.com/api/v4/projects/31358341","issues":"https://gitlab.com/api/v4/projects/31358341/issues","merge_requests":"https://gitlab.com/api/v4/projects/31358341/merge_requests","repo_branches":"https://gitlab.com/api/v4/projects/31358341/repository/branches","labels":"https://gitlab.com/api/v4/projects/31358341/labels","events":"https://gitlab.com/api/v4/projects/31358341/events","members":"https://gitlab.com/api/v4/projects/31358341/members"},"packages_enabled":true,"empty_repo":false,"archived":false,"visibility":"private","resolve_outdated_diff_discussions":false,"container_expiration_policy":{"cadence":"1d","enabled":false,"keep_n":10,"older_than":"90d","name_regex":".*","name_regex_keep":null,"next_run_at":"2021-11-17T11:06:05.761Z"},"issues_enabled":true,"merge_requests_enabled":true,"wiki_enabled":true,"jobs_enabled":true,"snippets_enabled":true,"container_registry_enabled":true,"service_desk_enabled":true,"service_desk_address":"contact-project+nova-dubai-first-31358341-issue-@incoming.gitlab.com","can_create_merge_request_in":true,"issues_access_level":"enabled","repository_access_level":"enabled","merge_requests_access_level":"enabled","forking_access_level":"enabled","wiki_access_level":"enabled","builds_access_level":"enabled","snippets_access_level":"enabled","pages_access_level":"private","operations_access_level":"enabled","analytics_access_level":"enabled","container_registry_access_level":"enabled","emails_disabled":null,"shared_runners_enabled":true,"lfs_enabled":true,"creator_id":713145,"import_status":"none","open_issues_count":1,"ci_default_git_depth":50,"ci_forward_deployment_enabled":true,"ci_job_token_scope_enabled":false,"public_jobs":true,"build_timeout":3600,"auto_cancel_pending_pipelines":"enabled","build_coverage_regex":null,"ci_config_path":"","shared_with_groups":[],"only_allow_merge_if_pipeline_succeeds":false,"allow_merge_on_skipped_pipeline":null,"restrict_user_defined_variables":false,"request_access_enabled":true,"only_allow_merge_if_all_discussions_are_resolved":false,"remove_source_branch_after_merge":true,"printing_merge_request_link_enabled":true,"merge_method":"merge","squash_option":"default_off","suggestion_commit_message":null,"merge_commit_template":null,"squash_commit_template":null,"auto_devops_enabled":false,"auto_devops_deploy_strategy":"continuous","autoclose_referenced_issues":true,"keep_latest_artifact":true,"external_authorization_classification_label":"","requirements_enabled":false,"security_and_compliance_enabled":true,"compliance_frameworks":[],"permissions":{"project_access":null,"group_access":{"access_level":30,"notification_level":3}}}

Getting merge request title. Argument provided : aa
Title obtained with -m option: aa
Merge request title : aa


Creating merge request
Merge request response: 

 {
  id: 135566287,
  iid: 420,
  project_id: 31358341,
  title: 'aa',
  description: '',
  state: 'opened',
  created_at: '2022-01-17T18:47:11.133Z',
  updated_at: '2022-01-17T18:47:11.133Z',
  merged_by: null,
  merged_at: null,
  closed_by: null,
  closed_at: null,
  target_branch: 'master',
  source_branch: 'test2',
  user_notes_count: 0,
  upvotes: 0,
  downvotes: 0,
  author: {
    id: 9114706,
    username: 'Naist4869',
    name: 'Naist4869',
    state: 'active',
    avatar_url: 'https://secure.gravatar.com/avatar/0f0f86d6a5dc99ca7bc0231d78ed1cd4?s=80&d=identicon',
    web_url: 'https://gitlab.com/Naist4869'
  },
  assignees: [],
  assignee: null,
  reviewers: [],
  source_project_id: 31358341,
  target_project_id: 31358341,
  labels: [],
  draft: false,
  work_in_progress: false,
  milestone: null,
  merge_when_pipeline_succeeds: false,
  merge_status: 'checking',
  sha: '107b225d762d99a7dbef4e8cb8b3434110aa12d0',
  merge_commit_sha: null,
  squash_commit_sha: null,
  discussion_locked: null,
  should_remove_source_branch: null,
  force_remove_source_branch: false,
  reference: '!420',
  references: { short: '!420', relative: '!420', full: 'nova_dubai/first!420' },
  web_url: 'https://gitlab.com/nova_dubai/first/-/merge_requests/420',
  time_stats: {
    time_estimate: 0,
    total_time_spent: 0,
    human_time_estimate: null,
    human_total_time_spent: null
  },
  squash: false,
  task_completion_status: { count: 0, completed_count: 0 },
  has_conflicts: false,
  blocking_discussions_resolved: true,
  approvals_before_merge: null,
  subscribed: true,
  changes_count: '96',
  latest_build_started_at: null,
  latest_build_finished_at: null,
  first_deployed_to_production_at: null,
  pipeline: null,
  head_pipeline: null,
  diff_refs: {
    base_sha: '30f1075da1f30c667fbb9c5e4bcd1dbf848e654a',
    head_sha: '107b225d762d99a7dbef4e8cb8b3434110aa12d0',
    start_sha: '4685eb2a2a70651e5c9a1f35c7247ccc0ef03e81'
  },
  merge_error: null,
  user: { can_merge: false }
}
