### ISSUE TITLE
Merge request not opening on correct repository.

### ISSUE THREAD

**Issue by BrOrlandi** [vishwanatharondekar/gitlab-cli#204]
I have two repositories in my organization:
https://gitlab.com/kassellabs/videomatik
https://gitlab.com/kassellabs/videomatik-sample

When I try to open a merge request using `lab merge-request` on `videomatik` repository, it's opening the merge request on the `videomatik-sample` repository. As it doesn't have the branch it just opens an empty merge request.

It may be related to something in the code that may use the URL prefix instead of the entire URL.
I did check if my remote is correct, and everything is correct.

The `lab merge-requests` command works fine, open the merge requests of the correct repo.

**Comment by BrOrlandi** [comment]
It's related when you run `gitlab.Projects.search` and it returns a list of projects that matches the project name. When you pick just the first element of the array it may get the wrong repo. I think it should run a search with a different argument if possible, or don't get the first element of the result array, find for the project those remote URL matches. I may send a quick fix on this soon.

**Comment by vishwanatharondekar** [comment]
This is fixed and merged in PR https://github.com/vishwanatharondekar/gitlab-cli/pull/211

Published a release 2.0.11 on npm as well.
