### ISSUE TITLE
`lab mr` command creates merge request with wrong project

### ISSUE THREAD

**Issue by Holinc19** [vishwanatharondekar/gitlab-cli#209]
For example, I have tow projects, `project-demo-management` and `project-demo`, and I run command `lab mr -b feature-bbb -t develop -m "demo" -a 12279` in `project-demo` , it would create a merge request in `project-demo-management`.

It may be wrong to get the target project by index zero. The wrong source code bellow.
```
project = project[0]
targetProject = targetProject[0]

```

**Comment by vishwanatharondekar** [comment]
This is similar to https://github.com/vishwanatharondekar/gitlab-cli/issues/204 . There is PR for same as well. Will get this merged over the weekend and publish a version with the fix. Thanks for patience.
