### ISSUE TITLE
[suggestion] gitlab url & token from git config

### ISSUE THREAD

**Issue by mathroc** [vishwanatharondekar/gitlab-cli#22]
if available `git config gitlab.url` & `git config gitlab.token` should be used instead of env vars so that it's easy to work on projects on different gitlab instances

**Comment by vishwanatharondekar** [comment]
Nice suggestion. Will implement. Happy to accept merge request.

**Comment by strk** [comment]
See my approach at it: https://github.com/NARKOZ/gitlab/issues/328#issuecomment-338310191
You basically do this from a wrapper, which is the one you use with `git lab`...

**Comment by vishwanatharondekar** [comment]
This is done in https://github.com/vishwanatharondekar/gitlab-cli/pull/50
