### ISSUE TITLE
[question] getting base & target branches

### ISSUE THREAD

**Issue by mathroc** [vishwanatharondekar/gitlab-cli#23]
I usually have my repositories setup like this:

```
$ git remote -v
origin  ssh://git@company.com:222/me/project.git (fetch)
origin  ssh://git@company.com:222/me/project.git (push)
upstream        ssh://git@company.com:222/source/project.git (fetch)
upstream        ssh://git@company.com:222/source/project.git (push)
$ cat .git/config
[branch "my-branch"]
        remote = upstream
        merge = refs/heads/master
```

when I run `gitlab-cli create-merge-request -v`

I get an error saying:

> Source project is not a fork of the target project

I have to specify both the base and the target. I have a wrapper that does this :

`gitlab-cli create-merge-request -p -b origin/$(git rev-parse --abbrev-ref HEAD) -t upstream/master "@$"`

is it the expected behavior ? can this be improved to automatically get the correct branch by default ? (the behavior of https://github.com/jsmits/github-cli seems sane)

**Comment by vishwanatharondekar** [comment]
@mathroc 
I think I know whats happening. This happens when your origin is manually created repo with the same name as that of upstream repo. This will not happen if you have forked the repo using fork button in the upstream repo. 

Let me know if the case is otherwise.

**Comment by mathroc** [comment]
I'm not sure what you mean, the forks I have have been created using the `fork` button in gitlab. your forks does not have the same name as the base repo ?

**Comment by beckje01** [comment]
I use forks as well and I don't have this issue let me check how my branches and forks are set up

**Comment by vishwanatharondekar** [comment]
I have this issue with one of my repo. I had created a repo manually named web. Then we created another repo in another user with same name web. When I tried creating merge request from my repo to this other users repo, I was getting this issue. Somehow gitlab doesn't allow creating merge request  if source is not a fork of target. 

But maybe @mathroc case is different.

**Comment by vishwanatharondekar** [comment]
Maybe this is related https://gitlab.com/gitlab-org/gitlab-ce/issues/20097

**Comment by vishwanatharondekar** [comment]
Deleted my previous comment about my issue to not confuse anyone.

**Comment by vishwanatharondekar** [comment]
@mathroc will be great if you can share the complete console log generated (sanitised obviously) using -v option when you are running into the issue.

**Comment by beckje01** [comment]
Is your master branch set to track the gitlab remote?

**Comment by mathroc** [comment]
I'm not sure why but I'm not having the same issue :

> verbose option used. Detailed logging information will be emitted.
> 
> 
> 
> Getting base branch information
> 
> Getting base branch name : 
> Executing git rev-parse --abbrev-ref HEAD
> Base branch name obtained : my-branch
> 
> Getting remote of branch  : my-branch
> Branch name obtained : my-branch
> Executing git config branch.my-branch.remote
> Remote obtained :  upstream
> 
> 
> Getting URL of remote :  upstream
> Executing  git config remote.upstream.url
> URL of remote obtained :  ssh://git@gitlab.my-company.com:2222/the-group/the-project.git
> 
> 
> gitlab host obtained :  gitlab.my-company.com
> 
> Project name derived from host : the-group/the-project
> 
> Getting gitlab project info for : the-group/the-project
> Base project info obtained : {"id":30,"description":"","default_branch":"master","tag_list":[],"public":false,"archived":false,"visibility_level":10,"ssh_url_to_repo":"ssh://git@gitlab.my-company.com:2222/the-group/the-project.git","http_url_to_repo":"https://gitlab.my-company.com/the-group/the-project.git","web_url":"https://gitlab.my-company.com/the-group/the-project","name":"the-project","name_with_namespace":"the-group / the-project","path":"the-project","path_with_namespace":"the-group/the-project","container_registry_enabled":true,"issues_enabled":true,"merge_requests_enabled":true,"wiki_enabled":true,"builds_enabled":true,"snippets_enabled":true,"created_at":"2016-10-05T12:41:04.000Z","last_activity_at":"2017-03-22T16:33:00.000Z","shared_runners_enabled":true,"lfs_enabled":true,"creator_id":2,"namespace":{"id":14,"name":"the-group","path":"the-group","kind":"group"},"avatar_url":"https://gitlab.my-company.com/uploads/project/avatar/30/img-darry-cowl-1443022516_580_380_center_articles-207158.jpg","star_count":0,"forks_count":7,"open_issues_count":3,"public_builds":true,"shared_with_groups":[],"only_allow_merge_if_build_succeeds":true,"request_access_enabled":true,"only_allow_merge_if_all_discussions_are_resolved":false,"permissions":{"project_access":null,"group_access":{"access_level":30,"notification_level":3}}}
> 
> 
> 
> Getting target branch information
> Remote branch name obtained : master
> 
> Getting remote of branch  : master
> Executing git config branch.master.remote
> Remote obtained :  upstream
> 
> 
> Getting URL of remote :  upstream
> Executing  git config remote.upstream.url
> URL of remote obtained :  ssh://git@gitlab.my-company.com:2222/the-group/the-project.git
> 
> Getting target project information
> Target project info obtained : {"id":30,"description":"","default_branch":"master","tag_list":[],"public":false,"archived":false,"visibility_level":10,"ssh_url_to_repo":"ssh://git@gitlab.my-company.com:2222/the-group/the-project.git","http_url_to_repo":"https://gitlab.my-company.com/the-group/the-project.git","web_url":"https://gitlab.my-company.com/the-group/the-project","name":"the-project","name_with_namespace":"the-group / the-project","path":"the-project","path_with_namespace":"the-group/the-project","container_registry_enabled":true,"issues_enabled":true,"merge_requests_enabled":true,"wiki_enabled":true,"builds_enabled":true,"snippets_enabled":true,"created_at":"2016-10-05T12:41:04.000Z","last_activity_at":"2017-03-22T16:33:00.000Z","shared_runners_enabled":true,"lfs_enabled":true,"creator_id":2,"namespace":{"id":14,"name":"the-group","path":"the-group","kind":"group"},"avatar_url":"https://gitlab.my-company.com/uploads/project/avatar/30/img-darry-cowl-1443022516_580_380_center_articles-207158.jpg","star_count":0,"forks_count":7,"open_issues_count":3,"public_builds":true,"shared_with_groups":[],"only_allow_merge_if_build_succeeds":true,"request_access_enabled":true,"only_allow_merge_if_all_discussions_are_resolved":false,"permissions":{"project_access":null,"group_access":{"access_level":30,"notification_level":3}}}
> 
> Getting merge request title. Argument provided :  test
> Title obtained with -m option:  test
> Merge request title :  test
> 
> 
> Creating merge request
> Merge request response : 
> 
 > { id: 399,
  > iid: 68,
  > project_id: 30,
  > title: 'test',
  > description: '',
  > state: 'opened',
  > created_at: '2017-03-22T16:35:18.025Z',
  > updated_at: '2017-03-22T16:35:18.025Z',
  > target_branch: 'master',
  > source_branch: 'my-branch',
  > upvotes: 0,
  > downvotes: 0,
  > author: 
   > { name: 'Mathieu Rochette',
     > username: 'mathieu',
     > id: 11,
     > state: 'active',
     > avatar_url: 'https://secure.gravatar.com/avatar/1a9570fcb8adbf7fd194f5835c8c3d3e?s=80&d=identicon',
     > web_url: 'https://gitlab.my-company.com/mathieu' },
  > assignee: null,
  > source_project_id: 30,
  > target_project_id: 30,
  > labels: [],
  > work_in_progress: false,
  > milestone: null,
  > merge_when_build_succeeds: false,
  > merge_status: 'unchecked',
  > sha: null,
  > merge_commit_sha: null,
  > subscribed: true,
  > user_notes_count: 0,
  > should_remove_source_branch: null,
  > force_remove_source_branch: null,
  > web_url: 'https://gitlab.my-company.com/the-group/the-project/merge_requests/68' }

the merge request is created but then it said " Source branch my-branch does not exist " on gitlab because it's looking for my-branch on the upstream project and not on my fork

this is happening in this part :


> Getting remote of branch  : my-branch
> Branch name obtained : my-branch
> Executing git config branch.my-branch.remote
> Remote obtained :  upstream

I'm not sure how, but instead it should find "origin" here. maybe we can get the default push remote a branch from git ( because I have there is `remote.pushdefault=origin` )

**Comment by vishwanatharondekar** [comment]
Got it. your my-branch is actually tracked by upstream branch. This allows you to do pull from master to your branch without specifying it. `remote.pushdefault=origin` makes sure that you always push to origin. 

While automatically trying to derive the branch remote its tracking remote is used which is upstream in this case. 

Solution for this is to either specify the remotes while creating the merge request or change the tracking remote of branch to origin. 

If you change the tracking remote to origin, you will need to specify the remote name while pulling like following. 

```
git pull upstream master
```

**Comment by vishwanatharondekar** [comment]
Closing this since there is no issue here. Problem is solved by specifying the remotes in branch names provided for the users remote url config setup.

**Comment by vishwanatharondekar** [comment]
@mathroc feel free to reopen if you face the original issue again. Share console log while doing that.
