### ISSUE TITLE
push before creating a merge request

### ISSUE THREAD

**Issue by mathroc** [vishwanatharondekar/gitlab-cli#24]
push the local branch before creating the merge request so that it works if we forgot (or are too lazy) to push it first

**Comment by vishwanatharondekar** [comment]
This is almost duplicate of https://github.com/vishwanatharondekar/gitlab-cli/issues/9 which I want to do. 
Although, in this you are asking to make a push rather than telling user. Will want to check what hub does.

**Comment by vishwanatharondekar** [comment]
Closing this as this is duplicate on #9 . Cleaning up issues.
