### ISSUE TITLE
Would be great if we can have option to list merge requests

### ISSUE THREAD

**Issue by hamxabaig** [vishwanatharondekar/gitlab-cli#29]
It'd be great to show open merge requests assigned to the user, or an option to list all of them currently opened.
`gitlab-cli list-merge-request open` or `gitlab-cli list-merge-request assigned` something like this.
What are your thoughts on it ? Happy to provide PR for this. 🎉

**Comment by vishwanatharondekar** [comment]
List merge request on the command line. We already have a command open merge requests, which opens web page of merge requests. Will it make more sense to add options to that command?

**Comment by hamxabaig** [comment]
@vishwanatharondekar Yes, we can use that. Gitlab adds filters in the URL so we can use it i think.

**Comment by vishwanatharondekar** [comment]
@hamxabaig have added options -a and -s to open-merge-request command. You can give it a try when you can.

**Comment by hamxabaig** [comment]
@vishwanatharondekar works pretty well 🎉  Thanks
