### ISSUE TITLE
Regular Expression Issue

### ISSUE THREAD

**Issue by vip30** [vishwanatharondekar/gitlab-cli#34]
I am currently facing one problem
My git link is https://www.company.com/cool/new-project/sample.git

The expected name of the project should be cool/new-project/sample.git
but the regular expression only cut it to new-project/sample.git
Then the server return 404 

Would it be possible that the project name can be passed by parameter or modify the regular expression so the project name can be used?

**Comment by vishwanatharondekar** [comment]
@vip30 I have created merge request to fix the regular expression problem. I will merge it after testing it locally for some time. You can help me testing this as well by installing from the branch like following. 

```
npm install https://github.com/vishwanatharondekar/gitlab-cli.git#project-regex-fix -g
```

**Comment by vishwanatharondekar** [comment]
@vip30 would be great if you can confirm that this branch is working fine for your case by commenting here.

**Comment by vip30** [comment]
I think it's ok 
Thanks for your help
