### ISSUE TITLE
[question] Publish as npm module

### ISSUE THREAD

**Issue by vishwanatharondekar** [vishwanatharondekar/gitlab-cli#4]

**Comment by vishwanatharondekar** [comment]
@beckje01 @mathroc. I didn't do this yet because I couldn't find a good name which is not already taken at npm registry.

Names already taken 

1. gitlab-cli
2. cli-gitlab
3. gitlab
4. lab-cli

Given above, do you have any good suggestion on which name I can publish this so installing is clean and easy. 

One that comes to my mind which is available is glab-cli. Might even add glab-cli as command along with current command.

**Comment by mathroc** [comment]
what about starting with `git-` (and the binary too) so that it can be called as git command (eg: `git lab create-merge-request`)

so I'm suggesting:

* git-lab
* git-glab
* git-gl

**Comment by beckje01** [comment]
`gitlab-hub` since this i based on hub?

**Comment by vishwanatharondekar** [comment]
@mathroc Thanks for suggestion. Got to know something new. We can expose our command as a subcommand to git. 

Unfortunately git-lab is also taken on npm registry. https://github.com/intesso/git-lab. Happened only last month I guess. 

How about `git-lab-cli` and then exposing only lab or lab-cli as command. So following works.

```
git lab create-merge-request
```

or 

```
git lab-cli create-merge-request
```

@beckje01 Thanks for the suggestion, but I will not want to add hub to the name. I don't think we need it in the name. A note in the readme is enough I guess.

**Comment by mathroc** [comment]
👍 for `git-lab-cli` as the package name & `git-lab` as the binary command (I don't think cli is useful there)

**Comment by vishwanatharondekar** [comment]
Took me almost a year to get this done. Better late than never. Find here https://www.npmjs.com/package/git-lab-cli
