### ISSUE TITLE
Feature Request: Assignee support

### ISSUE THREAD

**Issue by damianoneill** [vishwanatharondekar/gitlab-cli#46]
Hi @vishwanatharondekar, have you considered adding option support for setting the assignee for e.g. 

````bash
-a, --assignee [optional] Assignee for the merge request
````

As before happy to test the functionality in our environment.  

Thanks,
Damian.

**Comment by vishwanatharondekar** [comment]
You mean adding assignee while creating merge request?

**Comment by damianoneill** [comment]
@vishwanatharondekar yes thats exactly it.

**Comment by vishwanatharondekar** [comment]
@damianoneill  Given that I have added that in open-merge-requests it should be easy to integrate this into create-merge-request now. Will spend some time to get this done.

**Comment by damianoneill** [comment]
Thanks @vishwanatharondekar, much appreciated.

**Comment by damianoneill** [comment]
@vishwanatharondekar @stevelacey thanks guys, works perfectly.
