### ISSUE TITLE
Print by default

### ISSUE THREAD

**Issue by stevelacey** [vishwanatharondekar/gitlab-cli#52]
I think the `-p` option should be default for all commands, and there should be a flag for opening

The `merge-requests` command could actually be made to work like `hub issue` in that by default it uses the API to list out merge requests (on that note `lab issue` would be handy too)

Afaik most tools require you do something like `open $(echo 'http://example.com')` to open, i.e. they don't support it internally

Afaik this wouldn't break any BC in CI's given they'll be using the `-p` flag which can still be supported even though it's default and redundant

**Comment by vishwanatharondekar** [comment]
Yes. Makes sense. This wouldn't break for CI so a safe change. People like me who have created aliases would have to make amends for adding open option in their commands.

**Comment by carlosen14** [comment]
Yes it broke CI.. now it says `error: unknown option --print`

**Comment by vishwanatharondekar** [comment]
@carlosen14  Let me add the option back which wont do anything. Will that work for you?

**Comment by vishwanatharondekar** [comment]
Although I will prefer people moving away from the option.

**Comment by stevelacey** [comment]
Yeah make it do nothing / set print.. even though print is the default :+1:

**Comment by carlosen14** [comment]
> Although I will prefer people moving away from the option.

It is not the best case, doing this, you are not making it backward compatible, then move it to a new major version `3.0.0`

**Comment by carlosen14** [comment]
> @carlosen14 Let me add the option back which wont do anything. Will that work for you?

yes, this is the best, as @stevelacey said, if the option is present or not, it will print it anyway.

**Comment by carlosen14** [comment]
fixed with #75
