### ISSUE TITLE
MR cannot be created if multiple remotes are defined

### ISSUE THREAD

**Issue by holgerstolzenberg** [vishwanatharondekar/gitlab-cli#56]
If multiple remotes are defined on the project, the tool fails to detect the default target branch via the `git config branch.master.remote` command.

This also occurs if the specific config value is not set.

Workarounds are:
* explicitly specify the target remote and branch via `-t origin/master`.

**Comment by vishwanatharondekar** [comment]
@holgerstolzenberg 
Default target branch is taken from gitlab project info and not local master branch. I am not sure if I will want to change it to use local master branch. 

Explicitly setting the target branch is available as you mentioned and you can use it for now. Will want to know about the case in detail if you can provide more information.

**Comment by holgerstolzenberg** [comment]
Okay I just double checked if the MASTER is set as the default branch and tried to create another MR. It worked. Maybe I was mislead. It might relate to the fact the I had two remotes defined afore.

**Comment by vishwanatharondekar** [comment]
If no arguments are given. It works as follows.

1. get current branch
2. get its remote
3. Obtain project name from remote
4. Fetch project info obtained from remote and project name from gitlab
5. Use default branch in gitlab as target branch. 

It doesn't matter if you have multiple remotes. Providing remotes as arguments is also supported as you already know. I am closing this assuming there is no problem here. Let me know if you need more help.
