### ISSUE TITLE
Command failed: git config branch.xxx.remote

### ISSUE THREAD

**Issue by Sharcoux** [vishwanatharondekar/gitlab-cli#57]
When I try to do

`lab merge-request`

on the branch xxx I wish to merge, I get

```
Error occured :
 Error: Command failed: git config branch.xxx.remote
```

**Comment by vishwanatharondekar** [comment]
This is happening because your local branch doesnt have upstream branch set. 

Do it like following 

```
git branch -u origin/<branch-name>
```

To avoid doing this next time always push with using -u option which sets the local branch to be tracked with upstream branch. 

```
git push origin <branch-name> -u
```

**Comment by Sharcoux** [comment]
Oh, ok! Thanks for the hint. I will add this to my git config.
