### ISSUE TITLE
Project info fetch failed : TypeError: Cannot read property 'headers' of undefined

### ISSUE THREAD

**Issue by kdebski85** [vishwanatharondekar/gitlab-cli#60]
`lab browse `
works for me without any problem.

However, when executing
`lab create-merge-request -v -b "some_branch" -t "some_branch" -m 'some_message'`

the output is:
> Project info fetch failed : TypeError: Cannot read property 'headers' of undefined

I am using GitLab Community Edition 8.17.8 and gitlab-cli version 1.0.2.
If I change gitlab.url to some non-existing host, the result is the same.
Additionally, -v option does not print anything more (it should print request and response).

My gitlab server contains multiple projects organised in multiple groups.
gitlab.url points to the root path of the server (like "https://gitlab.yourcompany.com")
I also configured gitlab.token.

Compare option also fails:
`lab compare -v -b "feature/abc" -t "develop"`

> Getting base branch name :
> Argument provided : feature/abc
> Branch name obtained : feature/abc
> Base branch name obtained : feature/abc
> 
> Getting remote of branch : feature/abc
> Branch name obtained : feature/abc
> Executing git config branch.feature/abc.remote
> Remote obtained : origin
> 
> 
> Getting URL of remote : origin
> Executing  git config remote.origin.url
> URL of remote obtained : git@my_gitlab_server:some_group/some-project.git
> 
> Project info fetch failed : TypeError: Cannot read property 'headers' of undefined`

**Comment by vishwanatharondekar** [comment]
Are you new user or this was working before for you and has stopped working suddenly?
Can you try upgrading to latest and check if you can still see the issue?

```
npm i git-lab-cli@latest
```

**Comment by kdebski85** [comment]
@vishwanatharondekar I am a new user.
I tried
`npm i -g git-lab-cli@latest`
and
`npm i -g npm`
They were successful, but there is no difference. compare and create-merge-request still fail.

Can outdated version of gitlab be a problem?
I am using 8.17.8 and I cannot upgrade.
Also when I set gitlab.url to some non-existing server, the error is the same, but I need to wait a few seconds.

**Comment by vishwanatharondekar** [comment]
Can you try version 1 then.

```
npm i -g git-lab-cli@1
```

**Comment by kdebski85** [comment]
@vishwanatharondekar 

I was able to create MR with git-lab-cli@1 but:
1. "-r" resulted in "error: unknown option `-r'"
2. "-t" option did nothing. MR was created with develop (default) branch as a target.
3. "-m" option did nothing. Notepad window popup asking me about the message.
4. "-a" option did nothing. MR was unassigned.

I ran the following command:

`lab mr -v -t 'some_target_branch' -m 'some message' -a 'some user'`

**Comment by vishwanatharondekar** [comment]
`-r` was added as part of 2.0 update. So thats expected. 

Other options are available in 1.x and should have worked. Let me verify whats happening. I use version 1 daily as well using these options.

**Comment by vishwanatharondekar** [comment]
I tried with version 1.0.2 and it works as expected. Not sure why the options are not working at your end. Which OS you are on?

**Comment by kdebski85** [comment]
I am using Windows 10 (OS is not my choice) with cmder shell (cmder.net).

I also tried to specify version 1.0.2 instead of 1, but there is no difference - t/m/a parameters are not working.
`npm i -g git-lab-cli@1.0.2`

**Comment by vishwanatharondekar** [comment]
Do you have git command running successfully.

What's output of following. 

```
git --version
```

**Comment by vishwanatharondekar** [comment]
Closing this since there is no reply. Assuming its working fine. Reopen if you are still seeing the same issue.
