### ISSUE TITLE
Cannot find module '@babel/runtime/core-js/object/define-property'

### ISSUE THREAD

**Issue by CVarisco** [vishwanatharondekar/gitlab-cli#61]
Hi!

thank you for sharing the tool with the community 👍 
I tried to use it and this is what happens to me, do you know what can I do for fix it? Do you know why this happens? 

![screen shot 2018-08-08 at 12 58 02](https://user-images.githubusercontent.com/7335613/43833378-d2c48b16-9b0a-11e8-8e74-2bae0e6860c2.png)

I'll here to help you if you need it.
Thanks

**Comment by vishwanatharondekar** [comment]
Closing this for lack for activity.
