### ISSUE TITLE
maybe it's not support ssh.

### ISSUE THREAD

**Issue by hungry0** [vishwanatharondekar/gitlab-cli#63]
emmm,one day,when i push local branch to remote,this error occurred: could not read Username for 'http://xxx': Device not configured. but when i use ssh ,this error fixed,but this plugin can not work well. so , my problem is if it's true,and can you help me slove this problem.

**Comment by vishwanatharondekar** [comment]
Can you paste the error coming. I use this daily witb my repos which use ssh.

**Comment by hungry0** [comment]
there is nothing happen, when i change gitlab.url=git@xxx.git，but ssh can work well actually，you can close this issue,sorry.
