### ISSUE TITLE
have you ever considered that auto accept merge-request using command line

### ISSUE THREAD

**Issue by hungry0** [vishwanatharondekar/gitlab-cli#64]
that's all.thanks

**Comment by vishwanatharondekar** [comment]
You mean adding a command for accepting the merge request if it is mergeable. 
Or 
You mean creating and merging the request at the same time?

**Comment by vishwanatharondekar** [comment]
Not sure if any of the tool provides this feature. I can implement though. We will have to call accept api after successful merge request creation if such option is provided. Happy to accept PR as well if you want to contribute.
