### ISSUE TITLE
Crash when using with pipelines

### ISSUE THREAD

**Issue by carlosen14** [vishwanatharondekar/gitlab-cli#69]
readlineSync asks for input gitlab url and token, but it crashes when using in gitlab pipelines.

Maybe adding a param so you don't ask for that when running on pipeline.

error is:
```
stty: invalid argument '-f'
/root/.npm/_npx/35/lib/node_modules/git-lab-cli/node_modules/readline-sync/lib/read.sh: line 49: can't create /dev/tty: No such device or address
```

**Comment by vishwanatharondekar** [comment]
@carlosen14 
readlineSync is used for initial setup if you havent provided the configuration needed. Configurations can be provided by two means. Either git config or global environment variables. You may use one of the both and it will skip the readlineSync. Read here https://github.com/vishwanatharondekar/gitlab-cli#configurations

**Comment by vishwanatharondekar** [comment]
Let me know if this is happening even without that. In that case requiring readlinesync itself might be a problem which might need a fix.

**Comment by carlosen14** [comment]
No, i knew i had to configure that previously, but you could throw an error like `No gitlab url configured` or `No gitlab token assigned` and `exit 1`. 

Just a suggestion to add a flag like `--pipeline` to internally not use `readlineAsync`, and if a param is missing, throw an error. 

My problem was, i was using a ci/cd variable and was protected, then this was showing as an empty string, i don't know why, maybe runner don't like to print out and 'protected' means this. But a tried other options before knowing the VAR was printing as an empty string.

At this point I would like a real error message. Not this. 
```
stty: invalid argument '-f'
/root/.npm/_npx/35/lib/node_modules/git-lab-cli/node_modules/readline-sync/lib/read.sh: line 49: can't create /dev/tty: No such device or address
```

I was putting config vars like this.
```
    - git config --add gitlab.url "https://gitlab.com"
    # Access token esta desprotegida, apenas asi lo lee
    - git config --add gitlab.token "$MERGE_REQUEST_ACCESS_TOKEN" #This was printing as empty because VAR was protected.

```

Excecuting like this.
```
    - >
      npx git-lab-cli merge-request 
        --base "origin/$ORIGIN_BRANCH" 
        --target "origin/$TARGET_BRANCH" 
        --message "AUTOMATIC MERGE REQUEST FROM PIPELINE" 
        --assignee "user" 
        --labels "pipeline,automr,deploy,$TARGET_BRANCH" 
        --print
```

by the way, great tool!!

**Comment by vishwanatharondekar** [comment]
I dont think adding an option to define use case is a good idea and then skip on basis of that. I will rather catch the error of readlineAsync and move on by saying no configuration found. 

This seems related https://github.com/anseki/readline-sync/issues/26

**Comment by carlosen14** [comment]
Ok, actually catch the error would be even better. Don't know what i was thinking..
