### ISSUE TITLE
Automatically merge if CI passes

### ISSUE THREAD

**Issue by csgillespie** [vishwanatharondekar/gitlab-cli#78]
Adding an option to automatically merge to master if the merge request passes CI (it's possible on via the web interface)

Thanks

**Comment by vishwanatharondekar** [comment]
I guess that comes into play only when you have set the CI. Will check if we have api support available for that.

**Comment by vishwanatharondekar** [comment]
Found this https://forum.gitlab.com/t/how-to-toggle-merge-when-pipeline-succeeds-via-gitlab-api/15065/5 after going through the documentation first for checking to see if there is such an option.
Looks like there isn't any option to do this with API as of now. Will keep this issue open for few more days to check.

**Comment by vishwanatharondekar** [comment]
After thinking more I realised that this operation is more of a merging the MR than creating it. I will need to support merge MR operation which seem to have this option available. 

https://docs.gitlab.com/ee/api/merge_requests.html#accept-mr

Let me see how I can add this use case in gitlab-cli.

**Comment by vishwanatharondekar** [comment]
Couldn't come back to this. If you want to merge from command line, you need MR id. I can't expect user to get merge id from UI, that will defeat the purpose of being cli utility. Any proposals on how to do this @csgillespie

**Comment by csgillespie** [comment]
Sorry, can't think of anything.

**Comment by xenomachina** [comment]
One way to programmatically set a MR to merge when the pipeline succeeds is to use [git push options](https://docs.gitlab.com/ee/user/project/merge_requests/#git-push-options):

    git push -o merge_request.merge_when_pipeline_succeeds

It would be nice if this could all be done in a single step, but this might be a workaround for some people.

**Comment by vishwanatharondekar** [comment]
Not doing this. Closing.
