### ISSUE TITLE
Why succed when baseBranch is not defined?

### ISSUE THREAD

**Issue by carlosen14** [vishwanatharondekar/gitlab-cli#79]
I am having this issue, this runs on gitlab pipeline, it couldn't create the mr but it exits 0 ..

```
ORIGIN_BRANCH dev
TARGET_BRANCH staging
$ npx git-lab-cli@2.0.4 merge-request --base "origin/$ORIGIN_BRANCH" --target "origin/$TARGET_BRANCH" --message "AUTOMATIC MERGE REQUEST FROM PIPELINE $ORIGIN_BRANCH > $TARGET_BRANCH" --labels "pipeline,automr,deploy,$TARGET_BRANCH" --print
npx: installed 103 in 13.781s
Couldn't create merge request
baseBranch is not defined # this is supposed to exit 1 to assume this couldn't make it
#
#
Job succeeded 
```

**Comment by carlosen14** [comment]
both branches do exist on repository.. dev and staging

**Comment by carlosen14** [comment]
this is the verbose
```
Verbose option used. Detailed logging information will be emitted.



Getting base branch information

Getting base branch name : 
Argument provided : origin/dev
Branch name obtained : dev
Base branch name obtained : dev

Getting remote of branch : origin/dev
Branch name obtained : dev
Remote obtained : origin

Getting URL of remote : origin
Executing  git config remote.origin.url
URL of remote obtained : https://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@gitlab.com/group/subgroup/repo.git


gitlab host obtained : gitlab.com
Couldn't create merge request
baseBranch is not defined
```

**Comment by carlosen14** [comment]
![image](https://user-images.githubusercontent.com/9368632/61833807-23e4a000-ae3b-11e9-9c49-10b290f3a5d1.png)

**Comment by carlosen14** [comment]
![image](https://user-images.githubusercontent.com/9368632/61833847-3e1e7e00-ae3b-11e9-817e-fb7c6e7721f4.png)

**Comment by vishwanatharondekar** [comment]
This looks like some unhandled case. Will have a look.

**Comment by carlosen14** [comment]
Made a few PR to help you handle this.. but still can't create the MR, don't know what that error means..

**Comment by vishwanatharondekar** [comment]
This is happening because regex is not able to handle the project names with more than one slashes in it or something similar causing the error to be thrown that please check if this is a valid git project. In my recent refactoring I changed some variables causing this case to break for variable not defined. Will fix both of these over the weekend.

**Comment by carlosen14** [comment]
ok thanks, this is a valid gitlab repository, a group/subgroup/repo.git

**Comment by vishwanatharondekar** [comment]
This is fixed in https://github.com/vishwanatharondekar/gitlab-cli/pull/81
