### ISSUE TITLE
Release support

### ISSUE THREAD

**Issue by Graunephar** [vishwanatharondekar/gitlab-cli#82]
Thanks for a great tool

Would love if this supported the release feature of GitLab. 

As I see there is no way to use releases on small projects that do not already use the API.  Being able to make a release directly from the command line would be very neat.

https://gitlab.au.dk/help/user/project/releases/index
https://gitlab.au.dk/help/api/releases/index.md

**Comment by vishwanatharondekar** [comment]
Aren't gitlab releases similar to git tags. Let me check the difference and come back to you on this.

**Comment by vishwanatharondekar** [comment]
Not doing this. Reopen if there are more users.
