### ISSUE TITLE
Error: Cannot read property 'green' of null

### ISSUE THREAD

**Issue by delanym** [vishwanatharondekar/gitlab-cli#85]
`lab merge-request -t TeP-2.0.1`

> Couldn't create merge request
> Cannot read property 'green' of null

gitlab-cli v2.0.6
git v2.24.0
GitLab Community Edition 10.6.3

**Comment by vishwanatharondekar** [comment]
Possible for you to use `-v` option and post the verbose log output here after sanitising it.

**Comment by delanym** [comment]
`lab merge-request -v -t master`

```
Verbose option used. Detailed logging information will be emitted.



Getting base branch information

Getting base branch name : 
Executing git rev-parse --abbrev-ref HEAD
Base branch name obtained : test

Getting remote of branch : test
Executing git config branch.test.remote
Remote obtained : origin


Getting URL of remote : origin
Executing  git config remote.origin.url
URL of remote obtained : git@10.4.0.228:suse/tep.git

Couldn't create merge request
Cannot read property 'green' of null

```

**Comment by vishwanatharondekar** [comment]
Looks like `URL.parse(gitlab.options.url).host` returned null. Can you check why that is the case. Whats the config set for gitlab.options.url . Check https://github.com/vishwanatharondekar/gitlab-cli#configurations to know how the config might have got saved. 

If you dont mind sharing what your gitlab.options.url is then I can help more by debugging myself.

**Comment by delanym** [comment]
It was set to HTTPS.
Can you rather make this a global config value?
Also, isn't there a more secure way of saving this? The .git/config file is readable by anyone.

**Comment by vishwanatharondekar** [comment]
You can set global environment variables as well. 

```
GITLAB_URL=https://gitlab.yourcompany.com
GITLAB_TOKEN=abcdefghijskl-1230
```

https://github.com/vishwanatharondekar/gitlab-cli#environment-variables

If this is not something you want let me know.

**Comment by delanym** [comment]
Thanks.
I don't want to store my PAT in plain text in an open file
Can you integrate with https://git-scm.com/docs/gitcredentials

**Comment by hacknlove** [comment]
I think I have the same problem.

```
$ lab mr -b newchat -t develop -m "improved search" -v
Verbose option used. Detailed logging information will be emitted.



Getting base branch information

Getting base branch name : 
Argument provided : newchat
Base branch name obtained : newchat

Getting remote of branch : newchat
Executing git config branch.newchat.remote
Remote obtained : origin


Getting URL of remote : origin
Executing  git config remote.origin.url
URL of remote obtained : git@gitlab.com:roadstr-team/backend.git


gitlab host obtained : gitlab.com

Project name derived from host : roadstr-team/backend

Getting gitlab project info for : roadstr-team/backend
Couldn't create merge request
Cannot read property 'green' of undefined
```

```
$ tail .git/config 
[gitlab]
        url = https://gitlab.com
        token = [edited]
```

**Comment by BrOrlandi** [comment]
I'm also having this problem. But it started after I upgraded from version 2.0.7 to 2.0.9.
Now I have installed version 2.0.7 and it's working.

It should be something caused by changes between those two versions. @vishwanatharondekar could you check it?

I can check it later and made a PR if I found anything.

**Comment by vishwanatharondekar** [comment]
Well it looks like there is conflict of how APIs are behaving for search and show commands. Can you tell which version of gitlab you are on @BrOrlandi

**Comment by vishwanatharondekar** [comment]
2.0.9 included a fix for https://github.com/vishwanatharondekar/gitlab-cli/issues/92 which might have caused this issue. Let me check and come back on this.

**Comment by koshyviv** [comment]
Have the same issue and am on version 2.0.9

```
vivek@xxx-0020:~/portal$ lab merge-request -b dev -t staging -v
Verbose option used. Detailed logging information will be emitted.



Getting base branch information

Getting base branch name : 
Argument provided : dev
Base branch name obtained : dev

Getting remote of branch : dev
Executing git config branch.dev.remote
Remote obtained : origin


Getting URL of remote : origin
Executing  git config remote.origin.url
URL of remote obtained : git@gitlab.com:gs/portal.git


gitlab host obtained : gitlab.com

Project name derived from host : gs/portal

Getting gitlab project info for : gs/portal
Couldn't create merge request
Cannot read property 'green' of undefined
```

**Comment by bwjohnson-ss** [comment]
Is there any resolution here? I just got the same error after migrating to a new laptop. I was probably on an older version on my old laptop, and was upgraded on the new.

**Comment by lukefan6** [comment]
Same issue here, version 2.0.9 won't work, but 2.0.7 is okay
