### ISSUE TITLE
Could I input Description without opening an editor?

### ISSUE THREAD

**Issue by wilsonleecn** [vishwanatharondekar/gitlab-cli#86]
is it possible to add an options for text-based description input?
Thanks

**Comment by vishwanatharondekar** [comment]
If `-m` option is provided that option is used. If not provided default text editor gets opened. 

You want to receive the message from standard input instead?

**Comment by wilsonleecn** [comment]
Hi, Thank you for reply. Perhaps I have some misunderstanding for gitlab. I find that -m value will be set as merge request title, not the description?

**Comment by vishwanatharondekar** [comment]
Yes. Description is available only in file based input where any content after a separate newline is taken as a description. 

For my understanding, whats the issue with using file based option?

**Comment by vishwanatharondekar** [comment]
I misread your initial query. You want option for description like `-d` or something like that. Confirm if you want this.

**Comment by wilsonleecn** [comment]
Yes Mr Arondekar. This is what I need.
Your tool helped me a lot. Thanks!

Vishwanath Arondekar <notifications@github.com> 于2020年1月31日周五 上午1:00写道：
