### ISSUE TITLE
`getURLOfRemote` return a remote URL with newline character after the project name

### ISSUE THREAD

**Issue by jaybowong** [vishwanatharondekar/gitlab-cli#88]
The returned value `remoteURL` contains a newline character in one of my projects. 
When I run `yarn lab mrs`, the value is like `https://git.mycompany.com/me/my-project%0A/merge_requests`.  There's a `%0A` after the project name.

But it's OK in another project. Don't know why.

https://github.com/vishwanatharondekar/gitlab-cli/blob/1a94539fb077df2b8d8a4da4e8d5684c638e3344/index.js#L193-L208

**Comment by vishwanatharondekar** [comment]
Merged and published on npm as 2.0.7
